name: Docker build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2  
    - name: Docker build
      run: docker build -t pywmlg:latest .
    # you can login to docker hub to push your image
    
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Docker push
    #   run: |
    #     docker push pywmlg:latest