
name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -e .
    - name: Test
      run: pytest
    - name: Formatting
      run: black --check */
    - name: Lint
      run: pylint --rcfile .pylintrc setup.py pywmlg tests/*
    - name: Type hinting
      run: mypy --config-file .mypy.ini pywmlg